language: android
sudo: false
install: true

addons:
  sonarcloud:
    organization: "more-mozzarella-inc"
    token:
      secure: "6f8734603c792f22114c1611a3297a1baaa76e94"

script:
  - ./gradlew sonarqube